name: "Run Checks"
on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  fmt:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - run: |
        nix fmt .
        git diff-files --quiet || (git -P diff; echo -e "\nNOT FORMATTED: run 'nix fmt .'"; false)

  build_packages:
    needs: fmt
    strategy:
      fail-fast: false
      matrix:
        package:
        - kernel_linux_6_12_rockchip.kernel
        - kernel_linux_6_15_pinetab.kernel
        - uBootRock64
        - uBootRockPro64
        - uBootPinebookPro
        - uBootROCPCRK3399
        - uBootPineTab2
        - uBootQuartz64A
        - uBootQuartz64B
        - uBootSoQuartzModelA
        - uBootSoQuartzCM4IO
        - uBootSoQuartzBlade
        - uBootOrangePiCM4
        - uBootRadxaCM3IO
        - uBootRadxaRock4
        - uBootRadxaRock4SE
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Free disk space
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo docker image prune --all --force
        df -h
    - uses: actions/checkout@v4
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi-aarch64 binfmt-support qemu-user-static
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - uses: cachix/cachix-action@v12
      with:
        name: nabam-nixos-rockchip
    - run: |
        nix build -L -j4 .#${{ matrix.package }}

  build_example:
    needs: fmt
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Free disk space
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo docker image prune --all --force
        df -h
    - uses: actions/checkout@v4
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi-aarch64 binfmt-support qemu-user-static
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - uses: cachix/cachix-action@v12
      with:
        name: nabam-nixos-rockchip
    - working-directory: ./example
      run: |
        nix build -L -j4 --accept-flake-config --override-input rockchip ..
